# Generated by Django 3.2.12 on 2022-02-19 16:56

import apps.providers.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('language', models.CharField(default='en', max_length=3, validators=[apps.providers.validators.validate_lang], verbose_name='Language')),
                ('currency', models.CharField(default='USD', max_length=3, validators=[apps.providers.validators.validate_currency], verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['name', 'email'],
            },
        ),
    ]
