# Generated by Django 3.2.12 on 2022-02-19 16:56

from django.contrib.postgres import operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("providers", "0001_initial")]
    operations = [
        operations.CreateExtension("postgis")
    ]
